{
 "title": "Spring Data",
 "time": { "from": "2026-03-23T22:45:37.963Z", "to": "2026-03-23T23:45:10.690Z" },
 "templating": {
  "list": [
   { "name": "service_name", "query": { "query": "label_values(service_name)" } },
   { "name": "env", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  { "title": "Hikari Connection Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HikariCP Connection Pool State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{service_name=~\"$service_name\", env=~\"$env\"}",
     "legendFormat": "active | {{ecs_task}}-{{version}}"
    },
    {
     "expr": "hikaricp_connections_idle{service_name=~\"$service_name\", env=~\"$env\"}",
     "legendFormat": "idle | {{ecs_task}}-{{version}}"
    },
    {
     "expr": "hikaricp_connections_pending{service_name=~\"$service_name\", env=~\"$env\"}",
     "legendFormat": "pending | {{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "Acquire Connection Latency",
   "type": "timeseries",
   "description": "purely the application thread's wait time to get a usable connection handed to it from the pool. If the pool has an idle connection ready, this is just a concurrent queue poll, sub-millisecond",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, version) (\n  rate(hikaricp_connections_acquire_seconds_bucket{service_name=~\"$service_name\", env=~\"$env\"}[5m])\n))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, version) (\n  rate(hikaricp_connections_acquire_seconds_bucket{service_name=~\"$service_name\", env=~\"$env\"}[5m])\n))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, version) (\n  rate(hikaricp_connections_acquire_seconds_bucket{service_name=~\"$service_name\", env=~\"$env\"}[5m])\n))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Connection Creation Time p99",
   "type": "timeseries",
   "description": "max and avg creation times for new connections (connections are dropped and created every x minutes, even for idle)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_max{service_name=~\"$service_name\", env=~\"$env\"}",
     "legendFormat": "max | {{ecs_task}}-{{version}}"
    },
    {
     "expr": "rate(hikaricp_connections_creation_seconds_sum{service_name=~\"$service_name\", env=~\"$env\"}[5m])\n/\nrate(hikaricp_connections_creation_seconds_count{service_name=~\"$service_name\", env=~\"$env\"}[5m])",
     "legendFormat": "avg | {{ecs_task}}-{{version}}"
    }
   ]
  },
  { "title": "Spring Data Repositories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Repository Invocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(spring_data_repository_invocations_seconds_count{service_name=~\"$service_name\", env=~\"$env\", state=\"SUCCESS\"}[5m])",
     "legendFormat": "success | {{repository}}.{{method}} | {{ecs_task}}-{{version}}"
    },
    {
     "expr": "rate(spring_data_repository_invocations_seconds_count{service_name=~\"$service_name\", env=~\"$env\", state=\"FAILURE\"}[5m])\n",
     "legendFormat": "failure | {{repository}}.{{method}} | {{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "Repository Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(spring_data_repository_invocations_seconds_sum{service_name=~\"$service_name\", env=~\"$env\"}[5m])\n/\nrate(spring_data_repository_invocations_seconds_count{service_name=~\"$service_name\", env=~\"$env\"}[5m])\n",
     "legendFormat": "avg | {{repository}}.{{method}} | {{ecs_task}}-{{version}}"
    },
    {
     "expr": "spring_data_repository_invocations_seconds_max{service_name=~\"$service_name\", env=~\"$env\"}",
     "legendFormat": "max | {{repository}}.{{method}} | {{ecs_task}}-{{version}}"
    }
   ]
  }
 ]
}