{
 "title": "Golden Signals",
 "description": "Golden Signals of services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service_name", "label": "Service Name", "query": { "query": "label_values(service_name)" } },
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  { "title": "Traffic Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Http Latency (p50 / p95 / p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le, version) (\r\n    rate(http_server_requests_seconds_bucket{service_name=~\"$service_name\", env=~\"$env\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p50 | {{git_sha_build}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, version) (\r\n    rate(http_server_requests_seconds_bucket{service_name=~\"$service_name\", env=~\"$env\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p90 | {{git_sha_build}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, version) (\r\n    rate(http_server_requests_seconds_bucket{service_name=~\"$service_name\", env=~\"$env\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p99 | {{git_sha_build}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Average per-second rate over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{service_name=~\"$service_name\", env=~\"$env\"}[5m])\r\n",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\nsum by (version) (\r\n  rate(http_server_requests_seconds_count{service_name=~\"$service_name\",env=~\"$env\",status=~\"5..\"}[5m])\r\n)\r\n/\r\nclamp_min(\r\n  sum by (version) (\r\n    rate(http_server_requests_seconds_count{service_name=~\"$service_name\",env=~\"$env\"}[5m])\r\n  ),\r\n  1e-9\r\n)\r\n)",
     "legendFormat": "5xx errors"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\nsum by (version) (\r\n  rate(http_server_requests_seconds_count{service_name=~\"$service_name\",env=~\"$env\",status=~\"4..\"}[5m])\r\n)\r\n/\r\nclamp_min(\r\n  sum by (version) (\r\n    rate(http_server_requests_seconds_count{service_name=~\"$service_name\",env=~\"$env\"}[5m])\r\n  ),\r\n  1e-9\r\n)\r\n)",
     "legendFormat": "5xx errors"
    }
   ]
  },
  {
   "title": "Inbound Bulkhead Permits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{service_name=~\"$service_name\", env=~\"$env\", name=\"webBulkheadFilter\"}",
     "legendFormat": "MAX_ALLOWED"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{service_name=~\"$service_name\", env=~\"$env\", name=\"webBulkheadFilter\"}\r\n-\r\nresilience4j_bulkhead_available_concurrent_calls{service_name=~\"$service_name\", env=~\"$env\", name=\"webBulkheadFilter\"}\r\n",
     "legendFormat": "USED"
    }
   ]
  },
  { "title": "JVM: Threads + CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Live Threads",
   "type": "timeseries",
   "description": "The total number of platform threads currently alive in the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{service_name=~\"$service_name\", env=~\"$env\"}",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "Daemon Threads",
   "type": "timeseries",
   "description": "Background threads. Do not keep the JVM alive. Ex GC helpers, schedulers, async internals.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{service_name=~\"$service_name\", env=\"$env\"}",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "Peak Threads",
   "type": "timeseries",
   "description": "The maximum number of live threads ever observed since JVM start. This value never goes down until restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{service_name=~\"$service_name\", env=~\"$env\"}",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "description": "Threads by JVM state.\n\nRUNNABLE: Actively executing or ready to run.\n\nBLOCKED: Waiting for a monitor lock.\n\nWAITING: Waiting indefinitely (park, wait).\n\nTIMED_WAITING: Waiting with a timeout.\n\nNEW: Created but not started.\n\nTERMINATED: Finished execution.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{service_name=~\"$service_name\", env=~\"$env\"}",
     "legendFormat": "{{state}} | {{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "If this goes high while threads are low → have blocking or heavy compute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "100 * process_cpu_usage{service_name=~\"$service_name\", env=~\"$env\"}\r\n",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  { "title": "JVM: Memory Heap + Non-Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Heap Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "100 *\r\nsum by (ecs_task, version) (\r\n  jvm_memory_used_bytes{area=\"heap\", service_name=~\"$service_name\", env=~\"$env\"}\r\n)\r\n/\r\nsum by (ecs_task, version) (\r\n  jvm_memory_max_bytes{area=\"heap\", service_name=~\"$service_name\", env=~\"$env\"}\r\n)\r\n",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "Heap Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by (ecs_task, version) (\r\n  jvm_memory_max_bytes{\r\n    service_name=~\"$service_name\",\r\n    env=~\"$env\",\r\n    area=\"heap\"\r\n  }\r\n) / 1000000",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by (ecs_task, version) (\r\n  jvm_memory_used_bytes{\r\n    service_name=~\"$service_name\",\r\n    env=~\"$env\",\r\n    area=\"heap\"\r\n  }\r\n) / 1000000",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum by (ecs_task, version) (\r\n  jvm_memory_used_bytes{\r\n    service_name=~\"$service_name\",\r\n    env=~\"$env\",\r\n    area=\"nonheap\"\r\n  }\r\n) / 1000000",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  { "title": "JVM: GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "description": "% of seconds spent in GC per second. Important: If this spikes, latency impacted",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "100 *\r\nsum by (ecs_task, version) (\r\n  rate(jvm_gc_pause_seconds_sum{\r\n    service_name=~\"$service_name\",\r\n    env=~\"$env\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "GC Pauses Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "60 *\r\nsum by (ecs_task, version) (\r\n  rate(jvm_gc_pause_seconds_count{\r\n    service_name=~\"$service_name\",\r\n    env=~\"$env\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  },
  {
   "title": "Average GC Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "100 * \r\nsum by (ecs_task, version) (\r\n  rate(jvm_gc_pause_seconds_sum{service_name=~\"$service_name\", env=~\"$env\"}[5m])\r\n)\r\n/\r\nsum by (ecs_task, version) (\r\n  rate(jvm_gc_pause_seconds_count{service_name=~\"$service_name\", env=~\"$env\"}[5m])\r\n)\r\n",
     "legendFormat": "{{ecs_task}}-{{version}}"
    }
   ]
  }
 ]
}